import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='flex h-screen'>
        {/** サイドバー */}
        <aside className="w-64 bg-gray-800 text-white flex flex-col">
          <div className="p-4 font-bold text-lg border-b border-gray-700">
            Sidebar
          </div>
          <nav className="flex-1 p-4 space-y-2">
            {/* <a href="/" className="block py-2 px-4 rouded hover:bg-gray-700">Home</a>
            <a href="/footballapi-players" className="block py-2 px-4 rouded hover:bg-gray-700">Football API Players</a>
            <a href="/players-master" className="block py-2 px-4 rouded hover:bg-gray-700">Player Master</a> */}
            <Link href="/" className="block py-2 px-4 rouded hover:bg-gray-700">Home</Link>
            <Link href="/footballapi-players" className="block py-2 px-4 rouded hover:bg-gray-700">Football API Players</Link>
            <Link href="/players-master" className="block py-2 px-4 rouded hover:bg-gray-700">Player Master</Link>
          </nav>
        </aside>

        {/** メインコンテンツ */}
        <main className="flex-1 flex flex-col">
          {/** ヘッダー */}
          <header className="bg-gray-100 p-4 text-left font-bold shadow-md">Header Text</header>

          {/** コンテンツ */}
          <Providers>
            <div className="flex-1 flex justify-left items-start bg-gray-50">
              {children}
            </div>
          </Providers>
        </main>
      </body>
    </html>
  );
}
