// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.1
// source: pkg/api/proto/squad-service.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SquadService_CreateSquad_FullMethodName = "/squadservice.SquadService/CreateSquad"
)

// SquadServiceClient is the client API for SquadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SquadServiceClient interface {
	CreateSquad(ctx context.Context, in *CreateSquadRequest, opts ...grpc.CallOption) (*CreateSquadResponse, error)
}

type squadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSquadServiceClient(cc grpc.ClientConnInterface) SquadServiceClient {
	return &squadServiceClient{cc}
}

func (c *squadServiceClient) CreateSquad(ctx context.Context, in *CreateSquadRequest, opts ...grpc.CallOption) (*CreateSquadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSquadResponse)
	err := c.cc.Invoke(ctx, SquadService_CreateSquad_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SquadServiceServer is the server API for SquadService service.
// All implementations must embed UnimplementedSquadServiceServer
// for forward compatibility.
type SquadServiceServer interface {
	CreateSquad(context.Context, *CreateSquadRequest) (*CreateSquadResponse, error)
	mustEmbedUnimplementedSquadServiceServer()
}

// UnimplementedSquadServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSquadServiceServer struct{}

func (UnimplementedSquadServiceServer) CreateSquad(context.Context, *CreateSquadRequest) (*CreateSquadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSquad not implemented")
}
func (UnimplementedSquadServiceServer) mustEmbedUnimplementedSquadServiceServer() {}
func (UnimplementedSquadServiceServer) testEmbeddedByValue()                      {}

// UnsafeSquadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SquadServiceServer will
// result in compilation errors.
type UnsafeSquadServiceServer interface {
	mustEmbedUnimplementedSquadServiceServer()
}

func RegisterSquadServiceServer(s grpc.ServiceRegistrar, srv SquadServiceServer) {
	// If the following call pancis, it indicates UnimplementedSquadServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SquadService_ServiceDesc, srv)
}

func _SquadService_CreateSquad_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSquadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquadServiceServer).CreateSquad(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquadService_CreateSquad_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquadServiceServer).CreateSquad(ctx, req.(*CreateSquadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SquadService_ServiceDesc is the grpc.ServiceDesc for SquadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SquadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "squadservice.SquadService",
	HandlerType: (*SquadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSquad",
			Handler:    _SquadService_CreateSquad_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/api/proto/squad-service.proto",
}
